### ISSUE TITLE
Asyncio Issues

### ISSUE THREAD

**Issue by Azareal** [Lawouach/WebSocket-for-Python#125]
```
Future/Task exception was never retrieved
future: Task(<closeit>)<exception=ConnectionResetError('Connection lost',)>
Traceback (most recent call last):
  File "C:\Python34\lib\asyncio\tasks.py", line 283, in _step
    result = next(coro)
  File "C:\(censored)\ws4py\async_websocket.py", line 85, in closeit
    yield from self.proto.writer.drain()
  File "C:\Python34\lib\asyncio\streams.py", line 286, in drain
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
```

Whenever a client attempts to connect, the server just seems to cough up this exception.

**Comment by bjura** [comment]
I have the same problem, not sure but it seems that error occurs when client sends something to the server, server is on asyncio, my client usecase is basically as simple as possible (of course in my application the client instance is kept alive for longer, I've tried also with 'client.run_forever()' on a separate thread but not any better):

```python
from ws4py.client.threadedclient import WebSocketClient

client = WebSocketClient('ws://localhost:8000/ws')
client.connect()
client.send('abc')
```

I have python 3.4.0.
There aren't any traces on the client side, I've tried also to send binary or BinaryMessage messages.

**Comment by Lawouach** [comment]
@bjura I couldn't reproduce the issue. I als have a feeling that immediatly calling send after connect on the threaded client will lead to race conditions.

**Comment by tito** [comment]
Please reopen if it still the case.

As per #204, connect is blocking, so send after connect on a threaded client will NOT lead to race conditions.
