### ISSUE TITLE
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by zaazbb** [Lawouach/WebSocket-for-Python#130]
when running WebSocketManager example met a error:

``` text
Traceback (most recent call last):
  File "D:\test\python\websockets-master\example\Copy of ws4py_server.py", line 24, in <module>
    client.connect()
  File "C:\Python34\lib\site-packages\ws4py\client\__init__.py", line 209, in connect
    self.sock.connect(self.bind_addr)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
```

the client example on https://ws4py.readthedocs.org/en/latest/sources/managertutorial/
os: windows xp sp3,  python3.4

**Comment by pkgandhi** [comment]
Hello, I have a similar issue. Do we have to put anything in the password if we do it via Windows Authentication via logging in via SQL Server Management Studio. Any help would be appreciated. Thank you!

**Comment by ultravires** [comment]
Hello, may your 'target' does not support **https**, like this: http://www.hacker97.cn/, but your "target = 'https://hacker97.cn/"

**Comment by sp98** [comment]
When installing MongoDB, you have 'complete' and 'custom' option. Go with 'custom' option. It solved this issue for me. Not sure why though.

**Comment by ujjwalrathod007** [comment]
I have the same error but I have already started the server before client.

**Comment by VIkash2601** [comment]
@zaazbb at #130 I did the same (placed the started the server before) but still having the same issue. Could you please help me?

**Comment by Lawouach** [comment]
Hey all, I haven't looked at this project for a long time so I apologise again if it is frustrating to you. I have moved one indeed. 

However, if there is a PR with fix someday for this one from the community, I'll be happy to release it.

**Comment by Ronald-Saunfe** [comment]
This error is raised when the client has failed to connect to the server.

- Ensure that your server is started this means that;
->the server has bind to the address and port and listening to an incoming connection

**Comment by Chedeshri** [comment]
I don't know why this issue is closed I have same error as most of you guys i.e "ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it".
Anyway i tried every possible solution mentioned in above list : 
1) Killing the application (IDE) - to check if any previous thread is holding the resource.
2) socket.close and socket shutdown to release the socket after use
3) running the server before the client
4) changing address from 'localhost' to '127.0.0.1'
5) changing the port from 50000 to other values.

apparently none of this had worked for me.

**Comment by lucky630** [comment]
found the solution after spending 2 hours of search
server.py file
`import socket
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
host = ''
port = 5555
s.bind((host, port))
s.listen(5)
while True:
   c, addr = s.accept()
   print('Got connection from', addr)
   c.send(b'Thank you for connecting')
   c.close()
`
client.py file
`import socket
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
host = 'server ip address..'
port = 5555
try:
    s.bind((host, port))
except socket.error as e:
    print(str(e))
s.connect((host, port))
print(s.recv(1024))
s.close()
`
This worked for me.

**Comment by Chedeshri** [comment]
Thank you so much for efforts to send the solution I will definitely try
this method.

Regards,
Shrinath Chede

**Comment by SalihOsman1** [comment]
I was able to resolve it by setting (debug=False) on my Flask server.  It worked for both (localhost, and 127.0.0.1). Hope that works for some folks!

**Comment by pietercusters** [comment]
What worked for me was uninstalling Java 12 and installing Java 8. Link for Windows: https://www.java.com/en/download/win10.jsp

**Comment by rohitgautamm** [comment]
change the port to 8080 or 8888 and the host to socket.gethostname()
hope it will help as it did help me
if the problem still exist please share the code

**Comment by Utkarsh22Ahuja** [comment]
Make sure that the value of IP address in server is exactly same for your client. Since client will connect to the server. Unfortunately the server will work only on 127.0.0.1 which is your machine and all other shall not work until you make your own virtual machine. On Unix systems this functionality will work on 127.0.*.* , but on windows only on 127.0.0.1.  
This is tested by me and its documentation is available on page number 12 of the book Foundation of Python Programming - Third edition, Brandon, John.

**Comment by chanandlerbing** [comment]
I was getting the same error .. make sure you are working on 3306 port if it isn't then add port="3307" or whatever port you are working on in the mysql.connector.connect `line`mydb = mysql.connector.connect(host = "127.0.0.1",port= "3307" ,user = "root",passwd="gautam4?")``

**Comment by muhammedayman** [comment]
if you are using wamp or xamp like software run it before you ran the command 
"python manage.py runserver" 
this is related with settings means if you are using mysql connection in your program

**Comment by ziyaetuk** [comment]
All i did was run "mongod", and tried connecting. The mongodb server needed to start.

**Comment by BiswajitGhoshal** [comment]
Why was this issue closed?  I couldn't find what solution was provided... !?  How and where should I have started running before making the call?

**Comment by njokuifeanyigerald** [comment]
am having the same issue whenever i use dj rest auth for django

**Comment by tamarAndEsti** [comment]
> I find out the reason of this error.
> Must start server before client. if no server running, the client will meet ConnectionRefusedError.
> I made a low level mistake.
> Close this issue, please.
> thank you.

how to do that?

**Comment by Lawouach** [comment]
I think, at this stage, most comments here are related to the common connection error that can occur on any software. They don't seem to be related to ws4py. I will therefore lock this issue.
