### ISSUE TITLE
WebSocketClient.closed() always returns code 1006 if reason string empty.

### ISSUE THREAD

**Issue by SamiAhola** [Lawouach/WebSocket-for-Python#137]
In websocket.py WebSocket.terminate(), the attribute "s.closing" gets tested for existence with:

---

```
    try:
        if not s.closing:
            self.closed(1006, "Going away")
        else:
```

---

This does not produce the desired result since "s.closing" is iterable.

As a fix I used the following code:

---

```
    try:
        if s.closing == None:
            self.closed(1006, "Going away")
        else:
```

---

**Comment by tito** [comment]
Already fixed in master
