### ISSUE TITLE
CherryPy: simple example of an echo server

### ISSUE THREAD

**Issue by JacquesBopp** [Lawouach/WebSocket-for-Python#140]
Hi, I tried your "simple example of an echo server" for CherryPy but I always get Errno 10060. I used exactly the same code as in the example. My CherryPy (version 3.5.0) server runs on a Webfaction server. Url and port used on the client side are 'ws://services.newsdetector.net:10510/ws'. If I run the client locally in a Putty session using 'localhost' and port 10510 everything works fine. I opened the port in the server firewall, so the firewall should not be the problem. Do you have any ideas what's going wrong?
Thank's for your response,
Jacques Bopp

**Comment by tito** [comment]
The demo bind the socket on 127.0.0.1. You can either try localhost or 127.0.0.1, but any others address that don't resolve to 127.0.0.1 wont work for the example.
