### ISSUE TITLE
Why is wsgiref not recommended for production?

### ISSUE THREAD

**Issue by Seanny123** [Lawouach/WebSocket-for-Python#143]
In the wonderful documentation it says:

> wsgiref is a built-in WSGI package that provides various classes and helpers to develop against WSGI. Mostly it provides a basic WSGI server that can be usedfor testing or simple demos. ws4py provides support for websocket on wsgiref for testing purpose as well. **It’s not meant to be used in production.**

Why isn't it recommended to be used in production? I was hoping to use `ws4py` in an application since it has such a delightfully minimal set of requirements, which is really important for me since my application (although it uses a web browser) needs to be able to be installed offline. Consequently, the fewer the requirements and the easier it is to install, the better.

Update: Just noticed that CherryPy is also basically requirement free and works with a wide range of Pythons. However, it might be helpful to note in the documentation the reasoning behind this warning. I'm going to compare the two and will make a pull request once I've figured out why.

**Comment by Ksengine** [comment]
wsgiref server is a WSGI wrapper around http.server(https://docs.python.org/3/library/http.server.html)
according to python documentation 

> Warning http.server is not recommended for production. It only implements basic security checks.

so **wsgiref only implements basic security checks.**
