### ISSUE TITLE
server, opened() is called each time a message is send

### ISSUE THREAD

**Issue by heppg** [Lawouach/WebSocket-for-Python#162]
Using websocket with cherrypy.
Whenever I pass a message from client to server, the server's opened-method is called.
I assume that this method should be called only once per successful connection.

**Comment by Lawouach** [comment]
Indeed, it should only becalled once when the connection was created. That is weird. Which versions of CP/ws4py are you running?

**Comment by heppg** [comment]
CherryPy==3.6.0
ws4py==0.3.4

The purpose of the code is: for a school class. I maintain a client for scratch, which allows for hardware access on raspberry pi. This code has an embedded web server to display current configuration and some events.

The code is derived from the Echo-Sample. But I use the RoutesDispatcher.
Some fragments attached: setup of cherrypy, the handler, fragment of the WebSocket implementation.
The client (firefox, javascript) reports connection open only once.

[code]WebSocketPlugin(cherrypy.engine).subscribe()
cherrypy.tools.websocket = WebSocketTool()

animationHandler = AnimationHandler()

dispatcher.connect(name='adapterAnimation'   , route='/ws'    , controller=animationHandler  , action='ws')
conf['/ws'] =   {
	'tools.websocket.on': True,
	'tools.websocket.handler_cls': AdapterAnimationWebSocket
}      
[/code]

[code]
class AnimationHandler(object):
    def ws(self):
        # you can access the class instance through
        handler = cherrypy.request.ws_handler
[/code]

[code]
class AdapterAnimationWebSocket(WebSocket):
    def __init__(self, sock, protocols=None, extensions=None, environ=None, heartbeat_freq=None):
        WebSocket.__init__(self, sock, protocols, extensions, environ, heartbeat_freq)
        print ("init")
        self.state = 0
        
    def opened(self):
        if ( self.state == 1):
            print ("AdapterAnimationWebSocket.opened (multiple)")
        if ( self.state == 0):
            self.state = 1
            print ("AdapterAnimationWebSocket.opened")
[/code]

**Comment by Lawouach** [comment]
I've never tried ws4py with the RoutesDispatcher so I'm wondering if there isn't some sort of corner case with that dispatcher.

How many times do you the log from the ws4py manager:

Managing websocket ...

?

**Comment by heppg** [comment]
ws4py - 243 - INFO - Managing websocket [Local => 127.0.0.1:8080 |
Remote => 127.0.0.1:58236]
is logged only once, although "AdapterAnimationWebSocket.opened
(multiple)" is reported multiple times.

When terminating connection (by closing client web page), I get
2015-04-06 22:28:31,108 - ws4py - 360 - DEBUG - Closing message received
(1001) ''
2015-04-06 22:28:31,108 - ws4py - 317 - INFO - Terminating websocket
[Local => 127.0.0.1:8080 | Remote => 127.0.0.1:58236]

Looks strange.
A threading problem ? The system is using multiple threads, and calling
the send function is from various threads (not decoupled by queues so far).

**Comment by Lawouach** [comment]
I must say I'm a bit puzzled honestly. I can't figure out where the opened() method could be called elsewhere. So, it could be a thread issue but I fail to identify it :(

**Comment by heppg** [comment]
Found the problem in my code (better: in front of my computer).
Websocket code is working fine.

Thank you for your support !

**Comment by Lawouach** [comment]
Well... that's a relief. Enjoy! :D
