### ISSUE TITLE
Is it possible to extract headers from WebSocketProtocol using asyncio

### ISSUE THREAD

**Issue by a904guy** [Lawouach/WebSocket-for-Python#169]
I've jumped down into the self.proto of the extended WebSocket class, but can't seem to find a way to get header information out from the yield considering it is just reading them and discarding them. Unless I'm overlooking something (It is late...)

I'd love to be able to get the Cookies out during the opened method if possible.

**Comment by Lawouach** [comment]
Heya,

Could you clarify which client you're using please? I can't recall a self.proto attribute.

Also, would it be possible to use the mailing-list instead for usage questions? :)

Thanks

**Comment by a904guy** [comment]
Absolutely, Didn't know there was one. I'll close the ticket out.
