### ISSUE TITLE
IOError(interrupted system call) on dropping privilages

### ISSUE THREAD

**Issue by EternityForest** [Lawouach/WebSocket-for-Python#172]
This is the same issue referenced here, I believe.
https://github.com/mopidy/mopidy/issues/718

The errors are IOErrors coming from the line
                events = self.poller.poll(timeout=self.timeout)
of the EPollPoller in manager.py

The errors appear on resume from suspend and when my process drops root(I am using Linux mint on a macbook)

My current workaround is to wrap that line in a try block, and treat IOErrors as if poll() had returned [ ].
I assume since the code does not specify edge polling, that any missed events will just be caught on the next poll.

I briefly tested the latest master but the issue appeared to still be present, my apologies if It's my fault and it's already been fixed.

**Comment by tito** [comment]
PR merged, thanks you!
