### ISSUE TITLE
Python 2.6 support

### ISSUE THREAD

**Issue by jcubic** [Lawouach/WebSocket-for-Python#182]
Any chance of support this version of python? I have python 2.6.6 on my shared hosting.

What features of Python 2.7 this library use so I can modify it to make it work for my case?

**Comment by jodal** [comment]
:-1:

Please read http://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html

There is also no security support for Python 2.6, ref [PEP361](https://www.python.org/dev/peps/pep-0361/):

> Python 2.6.9 is the final security-only source-only maintenance
> release of the Python 2.6 series.  With its release on October 29,
> 2013, all official support for Python 2.6 has ended.  Python 2.6
> is no longer being maintained for any purpose.

**Comment by Lawouach** [comment]
Hi there,

Sorry it took so long. I don't have a philosophical issue regarding supporting that version. However, it could represent a maintainance burden indeed. I'm already behind schedule when it comes to other issues.

@jcubic: Do you have a clear idea of what is missing so that it would work on 2.6?

Cheers

**Comment by jcubic** [comment]
Didn't have a chance to test it on 2.6, if I do I will let you know.

**Comment by jcubic** [comment]
the library is working on Python 2.6.6

**Comment by jcubic** [comment]
The wsgiref example run without erros but when I try to connect from the client I get error: `Uncaught DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.`

**Comment by jcubic** [comment]
Maybe it's because of the firewall because I have the same issue with perl websockets.
