### ISSUE TITLE
Missing 0.3.5 changelog and tag

### ISSUE THREAD

**Issue by jodal** [Lawouach/WebSocket-for-Python#192]
ws4py 0.3.5 was released to PyPI 2016-06-05. However, the git repo doesn't have a tag for the commit that was released nor an updated changelog. Both would be useful when reviewing the changes before updating the Debian package. Thanks!

**Comment by Lawouach** [comment]
Damn. You're right. I totally forgot about those :(

I will update them.

**Comment by stargaser** [comment]
The tag would be really useful -- after tagging, won't 0.3.5 show up on Github under releases?

**Comment by tito** [comment]
The tag and changelog have been updated for 0.3.5, now we know where we are :)
