### ISSUE TITLE
help me if my code!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! just a login 

### ISSUE THREAD

**Issue by ghost** [Lawouach/WebSocket-for-Python#197]
THIS IS THE ERROR
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Traceback (most recent call last):
  File "C:\Users\Daniel\Desktop\addon_login\teste.py", line 65, in <module>
    logged_in = doLogin(os.getcwd(),myusername,mypassword)
  File "C:\Users\Daniel\Desktop\addon_login\teste.py", line 50, in doLogin
    response = opener.open(req)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 549, in _open
    'unknown_open', req)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 1388, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: !doctype html>
<html lang="pt-br">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="profile" href="http>
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
import os
import re
import urllib
import urllib.request
import urllib.parse,http.cookiejar
from urllib.request import urlopen, URLError
import socket
# xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

myusername = 'danilo'
mypassword = '1234'
logged_in_string = 'ola'
# xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

def check_login(source,username):
        #logged_in_string = 'ola'

```
    if re.search(logged_in_string,source,re.IGNORECASE):
            return True
    else:
            return False
```
# xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

def doLogin(cookiepath, username, password):
        if not os.path.isfile(cookiepath):
                cookiepath = os.path.join(cookiepath, 'cookies.lwp')

```
    try:
            os.remove(cookiepath)
    except:
            pass

    if username and password:

            login_url = urllib.request.urlopen('http://www.lexdan.co').read().decode('utf-8')

            cj = http.cookiejar.CookieJar()
            cj = urllib.request.HTTPCookieProcessor(cj)

            header_string = [('User-Agent','Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36')]
            login_data = urllib.parse.urlencode({'log':'myusername', 'pwd':'mypassword', 'wp-submit':'Fazer login'})
            req = urllib.request.Request(login_url, login_data)
            proxy = urllib.request.ProxyHandler({'http':'http://107.1.39.55:3128'})
            opener = urllib.request.build_opener(cj,proxy)
            urllib.request.install_opener(opener)
            #urllib.request.urlopen('http://www.lexdan.co/login-2/', proxies=proxy)
            req.add_header('User-Agent',header_string)
            #binary_data = login_data.encode('UTF-8')

            cj = http.cookiejar.CookieJar()
            cj = urllib.request.HTTPCookieProcessor(cj)

            opener = urllib.request.build_opener(urllib.request.HTTPCookieProcessor(cj))
            response = opener.open(req)
            source = response.read()
            response.close()
            login = check_login(source,username)

            if login == True:
                    cj.save(cookiepath)
                    return login
            else:
                    return False
```
# xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

if **name** == "**main**":
    if myusername is '' or mypassword is '':
        print ('YOU HAVE NOT SET THE USERNAME OR PASSWORD!')
    else:
        logged_in = doLogin(os.getcwd(),myusername,mypassword)
        print ('LOGGED IN:'),logged_in

**Comment by TheSpeedyBlur** [comment]
Hey @sonaldynho,

I might be able to help if you post your source code on [pastebin](https://pastebin.com). (Or at least the affected part)

**Comment by tito** [comment]
This has nothing to do with this project.
