### ISSUE TITLE
py2exe / python2.7 / syntax error in "yield from" lines

### ISSUE THREAD

**Issue by erazor83** [Lawouach/WebSocket-for-Python#202]
Hi.

I'm a bit confused about my py2exe output right now.
Using ws4py on my webapp works nicely with python2 under windows and linux.

Now I tried to use py2exe which complains about "yield from" statements in ws4py code.

I'm wondering why python2 doesn't complain but py2exe does? Is there some kind of compatibility stuff I'm missing? Because "yield from" is not supported in python2.7 afaik.

Thanks for your response.

**Comment by erazor83** [comment]
I've noticed that I don't use this file and it's most likely for python3 only.

**Comment by tito** [comment]
The async_websocket module is used mostly with tulip server, which is for asyncio/tulip on Python 3. py2exe may import it while it should not, if you can put it in a black list, just do it :)
