### ISSUE TITLE
CherryPy does not use its own wsgiserver anymore, which ws4py depended on

### ISSUE THREAD

**Issue by JoeStaines** [Lawouach/WebSocket-for-Python#205]
From 9.0.0 onwards, cherrypy removed its wsgiserver module and is now using cheroot instead. Since ws4py tries to import from cherrypy.wsgiserver this causes everything to break.

Haven't looked into how big the change will need to be because of this, but at the very least i think there hsould be something indicating that ws4py doesn't support CherryPy from 9.0.0+

**Comment by ygbr** [comment]
This is what we get when trying to run ws4py with latest CherryPy (10.0.0) now:

```
File "/usr/local/lib/python3.6/site-packages/ws4py/server/cherrypyserver.py", line 72, in <module>
    from cherrypy.wsgiserver import HTTPConnection, HTTPRequest, KnownLengthRFile
ModuleNotFoundError: No module named 'cherrypy.wsgiserver'
```

**Comment by the7erm** [comment]
Are there any plans to make this compatible with cheroot?

**Comment by webknjaz** [comment]
Ref #206

**Comment by webknjaz** [comment]
@JoeStaines you may now close this issue.
