### ISSUE TITLE
client/__init__ protocols join fails line 326

### ISSUE THREAD

**Issue by isaacsanders** [Lawouach/WebSocket-for-Python#208]
From a coworker without a Github:

> I am trying to use the ws4py library with protocols and having issues. Line 326 in `client/__init__.py` is returning a TypeError related to the join statement. The value is a `b'string'` is an int and join is expecting a str. I was able to make this work by changing the line from `','.join(value)` to `','.join(str(value))`. I am fairly new to python and I am not sure this change will not have unintended consequences.

**Comment by tito** [comment]
I don't see anything in the code related to your message that can break right now.
If effectively, the join would have different types in the list, that wont work.

By the way `','.join(str(value))` would be wrong as well. Yes, read carrefully ^_^
