### ISSUE TITLE
PyPI latest release 0.3.5 does not include #205 and therefore breaks with cherrypy

### ISSUE THREAD

**Issue by matt-hammond-bbc** [Lawouach/WebSocket-for-Python#209]
Hello!

Please can I request that a new release be pushed to PyPI?

bbc/pydvbcss#13 is blocked because the fix #205 is not yet published to PyPI. Our project depends on ws4py and we currently recommend ws4py is installed via pip. The latest published package (0.3.5) does not yet include #205.

 Many thanks

**Comment by tito** [comment]
Hi, I'm going to release a new version 0.3.6 asap. Since the root issue is already closed, i'll close thisd one as well. (otherwise we could have many same issue asking for a new release due to unreleased merged issues) :)

Thanks
