### ISSUE TITLE
Any plans for a new release?

### ISSUE THREAD

**Issue by jolaf** [Lawouach/WebSocket-for-Python#288]

**Comment by Lawouach** [comment]
Hello @jolaf 

Sorry, as you have noticed, this repo is quiet. I don't really maintain it actively anylonger so I don't make plans around it. It remains open because folks use it and I don't want to take it from under their feet. 

I'll be looking at a new release if it makes sense though.

**Comment by jolaf** [comment]
I see, thank you a lot for looking after this project!

There's at least one important bug (#287) in the last release.
It has already been fixed in `master`, and that alone is worth the new release, from my perspective.

**Comment by Lawouach** [comment]
Thanks for raising these two. It helps me realise a new release might make sense.

**Comment by jolaf** [comment]
Also the last commit (#285) is an important one, there are some painful issues like #262 it would close.

**Comment by auvipy** [comment]
Yes a new release is planned

**Comment by jolaf** [comment]
> Yes a new release is planned

Amazing, thank you!

**Comment by jolaf** [comment]
Sorry, is there a chance for a new release this year?

**Comment by Lawouach** [comment]
Hello @jolaf I apologise, I don't personally maintain the repo any longer so I didn't realise the release had not happened. I'll do my best to issue one in the next few days.

**Comment by jolaf** [comment]
Great, thank you!

**Comment by Lawouach** [comment]
@jolaf I apologise again for the slow response. I have now made the release as 0.6.0

Keep in mind, this is not a project I maintain very much at all so be careful about relying too much on it. It will not disappear so that's okay but you noticed how slow things can be :)

**Comment by jolaf** [comment]
Thank you very much for your effort!
