### ISSUE TITLE
Move away from the class-based design

### ISSUE THREAD

**Issue by Lawouach** [Lawouach/WebSocket-for-Python#93]
It seems to me that the class-based design I've setup in ws4py is not really ideal. I don't see what precisely inheriting from WebSocket means at all. Perhaps something based around a simple registry of functions such as it's common to find in web framework dispatching? I've used something similar in my XMPP library.

https://github.com/Lawouach/headstock/blob/master/example/basic.py

I believe this would make ws4py act more like a library than a small framework.

Thoughts?

**Comment by tito** [comment]
The class design for now is ok. It even helped us to try fixing the issue before the next release in our own software ^^

I'll close this issue as it's more spiritual, and could possibility never been closed, as good code is really depending of the guys behind it.

For now, at least, let's not break the possibilities offers by this design in the current version.
